# Statistical tests


#Andiamo vedere tre!

*1. Normalita (con Grafichi e Shapiro Wilks)
*2. ANOVA
*3. LSD o HSD

#Normalita

#DOMANDA! Cos'e la normalita?

#TUTTI I AMBIENTI!
ggplot(mydata, aes(x=yield))+     # Plot general
  geom_histogram(colour="black")+   # Istogramma
  labs(y= "Frequenzia", x = "Resa (kg)")+  #Labels
  theme(text= element_text(size=15))   # Font size


#Non e molto normale. Andiamo vedere cosa c'eper ambiente!

#E per questo e utile il facet_wrap

ggplot(mydata, aes(x=yield))  +  # Plot general
  geom_histogram(colour="black", fill="white")+     # Istogramma
  labs(y= "Frequency", x = "Resa")+   # Etichette
  facet_wrap(mydata$loc ~ .)  +    # Fare un plot per localita
  theme(text= element_text(size=15))  # Font size

E chiaro que Molise e Sestola sono abastanza normali.
E che in Rotonda e Castronuovo si sono outliers que ci lasciano essere normalli.

  #----------------------------------------------------#

Normalita con test ----
Il test piu usato e Shapiro-Wilks

  # Ipotessi nula -> i dati sono normali -> p > 0.05
  # Ipotessi alternativa -> i dati non sono normali -> p < 0.05    
    
shapiro.test(mydata$yield)
?shapiro.test
  # Anormalisime! Confirmiamo quello
  # que abbiamo guardato nel plot
  # Quindi, non devo usare l'ANOVA in questo caso.


#Ma, si vediamo ogni ambiente, la cosa cambia.
#Per fare quello, una opzione sarebbe fare subsets
# e poi usare il test in ogni subset.

#Ma c'e un'altra opzione
#Questo paccheto ci permette fare
#il test Shapiro per fattore!!
install.packages("RVAideMemoire")
library(RVAideMemoire)

#Dai
byf.shapiro(yield ~ loc, mydata)

castronuovo = subset(mydata, loc == "Castronuovo")
shapiro.test(castronuovo$yield)

#Un ambiente non e normali! Ed il resto si!  
#Inoltre, la diferenzia tra 0,047 e 0,05 e molto bassa.
#Nel grafico vediamo que il problema e un outlier
#Per adesso lavoriamo cosi.


##ANOVA  -------------------------------------------


#Cos'e un ANOVA?
#Per me, scoprire si la varianza tra grouppi e
#piu grande di quella dentro i gruppi

#Lo facciamo in ogni ambiente
mydata_Sestola <- subset(mydata, loc == "Sestola")
myanova_Sestola <- aov(yield ~ gen, data=mydata_Sestola)
summary(myanova_Sestola)
#PR > 0.05
#Non ci sono dif. significative


mydata_Molise <- subset(mydata, loc == "Molise")
myanova_Molise <- aov(yield ~ gen, data=mydata_Molise)
summary(myanova_Molise)
#Non ci sono dif. significative

mydata_Rotonda <- subset(mydata, loc == "Rotonda")
myanova_Rotonda <- aov(yield ~ gen, data=mydata_Rotonda)
summary(myanova_Rotonda)
#no significativo

mydata_Castronuovo <- subset(mydata, loc == "Castronuovo")
myanova_Castronuovo <- aov(yield ~ gen, data=mydata_Castronuovo)
summary(myanova_Castronuovo)
#significativo


#TUtto quello si confirma graficamente
ggplot(mydata,  #la mia tabella
       aes(y= gen, #i genotipi 
           x=yield)) + # resa
  geom_boxplot()+ # geometria
  facet_wrap(loc~.) #facets


#----------------------------------------------------#
##LSD O HSD  -----------------------------------------

#Questi test si chiamano "POST HOC" e permetteno trovare diff. tra gruppi
#Ma solo si l'anova ci da differenze


#Il pacchetto agricolae e fatto a posto per la esperimentaziona agraria 
#e ci permette di calculare lo LSD (Least Significant Difference) 
#e lo HSD (Honest Significant Difference)
#(Sono molto similari, lo HSD es un po piu nuovo e piu usato)
install.packages("agricolae")
library(agricolae)


#Facciamo groups (lettere) per genotipo in Castronuovo
#La funzione e HSD.test()
#Oppure LSD.test()
myHSD_Castronuovo = HSD.test(myanova_Castronuovo, # il mio argumento e il resultado del ANOVA
                             "gen")  #La mia variabile "Trattamento" 
myHSD_Castronuovo                                    

#Il obgeto myHSD_Rotonda ha tanta roba
#La poso vedere con myHSD_Rotonda$
#OCHIO! IN questo caso, $ no chiama colonne, ma tabelle intiere
#Per esempio, consulta la statistica
myHSD_Castronuovo$statistics

#Ci interesa il ogetto che ha i gruppi
myHSD_Castronuovo$groups
groups = myHSD_Castronuovo$groups
groups

#Finalmente, si voglio fare un plot con i letri, 
#posso mettere i letri nella tabbella.
#MA! E un pochino tricky. 


#(Si e troppo complesso si puo fare oppure in power point)


#Andiamo

#Prima, devo aggiungere il nome del genotipo a la tabella
#(per adesso, sono soltanto i nomi delle rige)
groups = cbind(groups, rownames(groups))
#cbind significa column bind e ci lascia aggiungere colonne
groups
#Ma, il nome de la colonna e brutto.
names(groups)

#Lo cambio
colnames(groups)[3] = "gen"

#Uno la mia tabella de groups con quella degli dati
mydata_Castronuovo <- merge(mydata_Castronuovo, groups[,c(2,3)], by = "gen")

##Finalmente, il plot.
ggplot(mydata_Castronuovo,  #la mia tabella
       aes(x= gen, #i genotipi 
           y=yield)) +
  geom_boxplot()+ #geometria box plot
  geom_point(col = "tomato")+ #geometria punti rossi
  geom_text(aes(label= groups, #Lettere dei groups!
                y= 1000))+  # Posizione della letera iguale per tutti!
  labs( x= "Genotipo",    
        y= "Resa  (kg)",
        main= "Rotonda")+  #Titoli del grafo
  theme(text= element_text(size=15)) #Dimensione del testo.

#Prova a esportarlo cliccando sul "export" nella finestra giu a destra

#Fino qui arriva il nostro oggetivo
#Si c'e tempo seguiamo


#E come meto le lettere a canto delle "box"?
#Piu complicatino ma possibile
#Devo indicare la posizione "x" univocamente per ogni genotipo.
#Come ho due dati per genotipo, si lo faccio adesseo avro due lettere.

#Quindi, una opzione e calculare la media per genotipo.

#Ci vuole questo pachetto
install.packages("dplyr")
library(dplyr)

Il simbolo  %>% se chiama pipeline, e permete saltare de una funzione
a l'altra senza mettere tutti i argomenti.

Castronuovo_summary <- mydata_Castronuovo %>% #la mia tabella 
                       group_by(gen) %>% #la agruppo secondo genotipo
                       dplyr::summarize(yield_mean = mean(yield), #una colonna e la media
                                       yield_sd = sd(yield), # altra la desviazione standard
                                       groups = unique(groups)) # e altra i gruppi


write.csv(Castronuovo_summary,"datacastronuo.csv")
?write.csv

metto unique() per i gruppi perche 
cosi prende solo un dato per genotipo 
e da 18 rigghe paso a 9.

#Finalmente il plot
#Questa volta lo facciamo con i barre per che e anche bellino

ggplot(Castronuovo_summary,  #la mia tabella, questa volta ho scelto "Castronuovo Summary"
       aes(x= gen, #i genotipi 
           y=yield_mean)) + #
  geom_bar(stat= "identity", fill = "tomato") +
  geom_errorbar(aes(ymin= yield_mean - yield_sd,
                    ymax= yield_mean + yield_sd))+ #Il argomente stat= "identity" mi permmette que il asse "y" sea proprio la resa e non il numero de rigghe
  geom_text(aes(label= groups, #Lettere dei groups!
                y= yield_mean + yield_sd + 40))+  # Posizione della letera (la pos de la barra + 10 uds.)
  labs( x= "Genotipo",    
        y= "Resa  (kg)",
        main= "Rotonda")+  #Titoli del grafo
  theme(text= element_text(size=15)) #Dimensione del testo.


Cose sigue?
Special packages!
For next time diGGer, SPATS, GGE BiPLOT, PPB STATS!